
global function safe_execute(!func)
{
	try
	{
		return func()
	}
	catch (e)
	{
		print("ERROR: " + e)
	}
}